### ISSUE TITLE
deposit: document "all_versions" querystring parameter

### ISSUE THREAD

**Issue by slint** [zenodo/developers.zenodo.org#26]
Basically an entry in the parameters table of each relevant endpoint explaining what values the parameter accepts and the behaviour 

- [x] Deposit endpoint [table](https://developers.zenodo.org/#list)
- [x] Record endpoint [table](https://developers.zenodo.org/#records)

![image](https://user-images.githubusercontent.com/1814661/111617710-c35e5f80-87e3-11eb-8192-1039f376a45b.png)

**Comment by ctrl-alt-soneca** [comment]
<img width="835" alt="Captura de ecrã 2021-03-19, às 16 10 57" src="https://user-images.githubusercontent.com/79139616/111810333-ce8dba00-88cd-11eb-9476-34d3050fded4.png">
<img width="810" alt="Captura de ecrã 2021-03-19, às 16 11 08" src="https://user-images.githubusercontent.com/79139616/111810340-d0577d80-88cd-11eb-8e5e-9caee59cb5db.png">
