### ISSUE TITLE
"params" does not work in example

### ISSUE THREAD

**Issue by vsoch** [zenodo/developers.zenodo.org#34]
hey Zenodo! I'm not sure if this has changed over time, but the example that uses "params" doesn't seem to work (I just tested for this particular use case)
```python
        response = requests.get('https://zenodo.org/api/records',
                        params={'q': doi,
                                'access_token': self.token})
```
The above returns a 400 response, a bad request. However, changing to "json" seems to return a 200 response.
```python
        response = requests.get('https://zenodo.org/api/records',
                        json={'q': doi,
                                'access_token': self.token})
```
Is this something we could update in the developer docs? https://developers.zenodo.org/#records

**Comment by sunarch** [comment]
The `q` parameter is described in the docs as `Search query (using Elasticsearch query string syntax).`

The doi variable you use for that is (I'm guessing) a full DOI in the form of `10.5281/zenodo.xxxxxxx`.

However Elasticsearch tries to interpret this as a regular expression which is malformatted because of the lack of a closing slash:

> Regular expression patterns can be embedded in the query string by wrapping them in forward-slashes ("/"):

See also its documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_regular_expressions

**Comment by vsoch** [comment]
Don't you think the average user won't expect it to be a regular expression (and hit this error?)

**Comment by sunarch** [comment]
The error message in the 400 response body is useful I think, but you're right that the reference description can always be more detailed.

```JSON
'{"status": 400, "message": "The syntax of the search query is invalid."}'
```

**Comment by vsoch** [comment]
That would be great! I think an error message that tells people the syntax needs to be regular expression, etc. would solve my issue here. I'd hit the endpoint and then adjust my query appropriately. Thanks for your help!

**Comment by sunarch** [comment]
I added a PR for the documentation, I think combined with the current error message it should be referencable.

The error message comes from Invenio (invenio-records-rest):
https://github.com/inveniosoftware/invenio-records-rest/blob/82dc6e086fbd616a8d9676874ca08d39033f6108/invenio_records_rest/views.py#L56

If you would like to see the error message extended as well, I suggest opening an issue or PR there. However that is only the `records` part, the `deposits` and `licenses` also have a list endpoint with a search query parameter, so a consistent change across all of them would be a couple more steps.

**Comment by vsoch** [comment]
Thanks @sunarch ! I'm not using this actively anymore, so with your PR for the documentation I'm good to close the issue. Thank you again!

**Comment by sunarch** [comment]
Glad I could help:)
